### ISSUE TITLE
The ability to have "error expressions" - expressions that are only attempted when every other option fails

### ISSUE THREAD

**Issue by fresheneesz** [pegjs/pegjs#145]
The concept of "error expression" is one I didn't come up with on my own (tho I just made up the term "error expression" to describe it). I wish I could remember where I read about this idea - I can't find it anymore. I believe it was a parser generator that used syntax like:

ruleA = ruleB1
         | ruleB2
         ! errorExpressionA

ruleB1 = expressionA
       |  expressionB
       !  errorExpressionB

The pipe ( | ) character was used like / in PEG.js, and exclamation ( ! ) indicated that it was another expression that would only be called if _all_ other choices failed. In the example I wrote above, errorExpressionB would _not_ be attempted until ruleB2 completely failed - meaning that errorExpressionB does _not_ get attempted immediately after expressionB fails (like it would if it was a normal rule choice).

The idea was that this would make it far easier to write good error messages for your parser, without affecting the performance of the parser (since the error expressions aren't attempted until parsing for sure does not find a successful match). 

This would probably be pretty easy to implement - all you have to do is parse again excluding normal rules and only using error rules (basically render two parsers).

Update: the place I saw this error expression was the "naughty or" in language.js here: https://github.com/tolmasky/language . The website with the docs appears to be defunct tho : (

**Comment by tolmasky** [comment]
The second pass is necessary because if not the error expression can only be used at the topmost rules.
If you put error expression in deeper nodes, they will potentially incorrectly match earlier than parent
matches. For example:

Rule = A / B
B = "b" / throw "problem"
A = "a" / throw "problem"

Rule here is broken, because B can never match.

What we want is if the grammar *fails*, to then try some alternatives. With naughty OR you could do this:

Rule = A / B
B = "b" % "B" <Don't use capitals!>
A = "a" % "A" <Don't use capitals!>

Now when you feed it "A", you get "Don't use capitals" (a helpful error message), its in a logical place
place in the grammar (in the A rule), and it doesn't break parent rules.

**Comment by besquared** [comment]
+1 even though it's closed. @tolmasky described the problem very precisely. As for use cases the language.js readme lists the some pretty good ones.
