### ISSUE TITLE
Feature request: default labels

### ISSUE THREAD

**Issue by casey** [pegjs/pegjs#172]
I often find myself writing things like:

```a = b:b c:c d:d { /* do something with a, c, and d */ }```

It would be nice if things were labeled with the name of the rule if the label were unspecified:

```a = :b :c :d { /* do something with a, c, and d */ }```

This would only work for named rules, not expressions, so this would still throw an error:

```a = :(b / c / d) { /* wtf */ }```

PS And thanks for awesome parser generator! I just replaced a highly error-prone hand-coded recursive descent search query parser with a much tidier peg.js parser, and it feels goooooooood.

**Comment by bpow** [comment]
I'm not sure if this is as simple as in the proposed pull request (#349), but maybe that is most of the way there. The pull request does not address prefixed/suffixed rule references (the main type that I could foresee as useful would be ':$ruleref', but I'm not sure if/how you would want to go about implementing that without making too much of a special-case.

I didn't commit 'lib/parser.js' as part of the pull request, so a 'make parser' is required before 'npm test'

**Comment by johnsoftek** [comment]
Also see PR #335 which generates label default label names

**Comment by dmajda** [comment]
Looking at this issue again after 2 years (prompted by #349), I decided I don’t want this feature in PEG.js. Here are my reasons:

  1. It feels little too bit magicky, similarly to [ES6 object literal shorthand property names](https://developer.mozilla.org/cs/docs/Web/JavaScript/Reference/Operators/Object_initializer#New_notations_in_ECMAScript_6) which I also don’t like.

  2. [Recommended convention](https://github.com/pegjs/pegjs/issues/248#issuecomment-40890476) is to use `UpperCamelCase` for rules names and `lowerCamelCase` for label names in order to keep them clearly distinct. This feature would cause users to mix them up.

  3. This feature would encourage laziness in inventing label names. For example, consider this fragment (taken from the CSS example grammar):

    ```
    left:simple_selector S+ right:selector {
      return {
        type:       "Selector",
        combinator: " ",
        left:       left,
        right:      right
      };
    }
    ```

    One might be tempted to write the first line as just `:simple_selector S+ :selector`, but the resulting label names wouldn’t be as descriptive (selector type is unimportant here, the position is), resulting in harder to understand grammar and action code.

    I’d like to encourage users to *think* about label names, not give them an easy but often suboptimal default.

  4. I looked at bundled example grammars and there are not that many occurrences where this feature would be useful. So I consider its usefulness/weight ratio low.
