### ISSUE TITLE
NodeJS streams

### ISSUE THREAD

**Issue by andreineculau** [pegjs/pegjs#221]
I have a use case to parse a NodeJS stream, and I was wondering if that has already been on the table and ignored (if so, for what reasons)

There is also one specific case in comparison to the current string parsing: dealing with whatever data is streamed after the startRule has been fulfilled.

**Comment by lbeschastny** [comment]
Any plans on streams support?

**Comment by Mingun** [comment]
As by parsing parser can backtrack, it is necessary to keep some piece of the parsing sequence in memory. The ideology of a stream such is that it doesn't guarantee that it is possible to return back therefore buffering will be required. In order that buffering made sense, it is necessary to define when the part of a stream already is never required to us (if it not to do, it is necessary to buffer all stream that doesn't differ from the current behavior). It will occur when the parser passes a non-return point. It was necessary only to find such points.

One of sufficient conditions of that a point is a non-return point, that the current rule which is the last tried alternative at this position in the parsing sequence. If the rule doesn't match, there will be an parse error.

----
So far I have no ideas how further to formalize it, but at least I am sure that for part of situations this decision can be made in compilation time. In example
```pegjs
a = b с (d / f);
```
when `b` and `c` is parsed, parser reaches two non-return points, just after parsing this rules. The third non-return point will be reached after the parser parse the rule `f`.

More complicated example:
```pegjs
a = b+ a?;
```
After each parsing `b` parser reaches non-return point.

**Comment by dmajda** [comment]
@lbeschastny There are no plans for the immediate future.

There are many use cases for streaming with different constraints and motivations, plus there are problems stemming from the nature of PEGs which @Mingun rightly pointed out. As I said [before](https://github.com/pegjs/pegjs/issues/221#issuecomment-40919259), my preference is for interested users to explore this topic by writing a plugin (or even multiple plugins) which can possibly later serve as a base for implementation in core PEG.js.

**Comment by lbeschastny** [comment]
@Mingun @dmajda just a quick note based on the language I'm currently parsing with `pegjs`.

In many languages it should be possible to manually define all "non-return" grammar rules. Reaching one of those rules will tell the parser that all currently buffered data could be safely flushed.

Automatic non-return points detection will require a pretty deep analysis of the grammar, but in most practical cases it could be done manually very easily.

**Comment by Seb35** [comment]
[andreineculau](#issuecomment-40964344) commented on 21 Apr 2014:
> And regarding the 2nd part of the issue
> 
> > There is also one specific case in comparison to the current string parsing: dealing with whatever data is streamed after the startRule has been fulfilled.
> 
> Meanwhile I stubbed a solution based on the error returned - if the parser expected the end of input but found more, then the position of the error is all you need.

I propose a feature “partial match”  #645, which is a more integrated solution but the same thing you described in this comment.

**Comment by Seb35** [comment]
Reading this discussion, I’m not really sure I understand well the situation: is the (node) stream supposed to be a succession of segments, each captured by some PEG rule? If so, the issue is that, given the current position of the stream, either there are more characters than expected by the PEG rule, either there are not enough characters than expected by the PEG rule (either it is exactly what is expected and it is fine), right?

If the problem here can be decomposed into these two sub-problems, it could correspond to #645 for the first sub-problem (remaining characters) and possibly #607 for the second sub-problem (not enough characters).

Wondering myself how should behave the parser in the case of an unrecognised input (which will block indefinitely the stream, like a low surrogate code unit in an UTF-16 text without a preceding high surrogate code unit), I guess the parser should be defined to try to resynchronise itself (e.g. accept the lone low surrogate and discard it or mark it specifically) or emit a fatal error depending on the external requirements. And relatedly to the [comment by Migun on 31 Jan 2016](https://github.com/pegjs/pegjs/issues/221#issuecomment-177457362), I guess it is to the grammar writer to be careful about return points: in my UTF-16 example, the first high surrogate should not be captured unless followed by a low surrogate (in this case capture the two surrogates and increment the cursor by 2) or, if we try to recover from malformed UTF-16 texts, followed by another high surrogate (in this case only capture the first surrogate and increment the cursor by 1).
