### ISSUE TITLE
Please add endColumn, endLine, endOffset to the API

### ISSUE THREAD

**Issue by qbolec** [pegjs/pegjs#246]
When integrating PEG.js with ACE editor it really helps to know where each node of AST starts and ends, so you can for example highlight errors (i.e. type errors in a program, not just errors in parsing).
The API supports column(), line() and offset() functions which give the precise information about the beginning of an AST node.
The more difficult part is to learn where does it end.
I've worked around it by using `endOffset=offset()+text.length` and then trying to find specific line and column in which `endOffset` is located, but it seems to be quite complicated (it's hard to do it faster than in O(log n) time, and hard to do it right in presence of CR+LF mixups).
I believe that endLine and endColumn could be provided by API in O(1) making it both faster and less error prone.

**Comment by dmajda** [comment]
I moved this after 1.0.0 as I’d like to get to that version quickly. I’m now mostly focusing at polishing existing functionality and I’m deferring minor features that “only” fix annoyances (which this issue is because there is a workaround).

**Comment by dmajda** [comment]
I changed my mind and implemented this for 0.9.0 already — mostly because I figured out the right API (hopefully), the implementation wasn’t that hard, and because I want to add location info to `GrammarError` soon and it felt wasteful to do it one way and then redo it later. For details, [see the relevant commits](https://github.com/pegjs/pegjs/compare/e75f21dc8f0e66b3d87c4c19b3fcb8f89d9c3acd...d1fe86683b75d29ef52495ad643ca6b064d6a5f5).

@Mingun @kwesibrunee Thanks for exploring the topic, I drew inspiration form your approaches.

@Mingun I’ll probably add some comment later on why I did this differently than you did in #225 and why I didn’t accept your PR right away.
