### ISSUE TITLE
return from initializer

### ISSUE THREAD

**Issue by andreineculau** [pegjs/pegjs#275]
I discovered that the initializer can return immediately. See http://peg.arcanis.fr/1S0wNS/

1. constructive complaint: should be documented
2. I wonder if that is by design, or just a side-effect? since I'm writing the actions in CoffeeScript, I'll always have to handle its "always return by design"

**Comment by dmajda** [comment]
The possibility of returning from the initializer is an inevitable side effect of how PEG.js works. If I don’t want want parser internals to leak into the global scope (which I certainly don’t) I need to put initializer/action/predicate code into *some* function because that’s the only way to create a new scope in JavaScript. That function can be returned from.

> constructive complaint: should be documented

I don’t think so. There is ton of various side effects which stem from the fact that your code gets embedded into some wrapper. This is true for any parser generator with semantic actions.

> I wonder if that is by design, or just a side-effect?

Side-effect.

> since I'm writing the actions in CoffeeScript, I'll always have to handle its "always return by design"

Unless I am mistaken, you need to handle this only if your code is inside a function.

I don’t think there is anything to do here ⇒ closing.

-----

As a side note, I briefly looked at your [commit](https://github.com/andreineculau/pegjs-override-action/commit/4aa1cc9337ff2f36af5fd74d3dbecf6c1282b600) linked above. The solution you chose prevents defining variables/functions in the initializer that can be used in actions & predicates. This is a major inconvenience.
