### ISSUE TITLE
Strings

### ISSUE THREAD

**Issue by futagoza** [pegjs/pegjs#292]
I've noticed in the javascript example that you take a pretty routed step to make sure everything is correct, and was wondering why not use 'JSON.stringify'.

For example, something like this works as well (is  self contained, try it in the online editor):
```d
StringLiteral "string"
  = '"' chars:DoubleStringCharacter* '"' {
      return { type: "DoubleString", value: JSON.stringify(chars.join("")) };
    }
  / "'" chars:SingleStringCharacter* "'" {
      return { type: "SingleString", value: JSON.stringify(chars.join("")) };
    }

DoubleStringCharacter
  = '\\' '"' { return '"'; }
  / !'"' SourceCharacter { return text(); }

SingleStringCharacter
  = '\\' "'" { return "'"; }
  / !"'" SourceCharacter { return text(); }

SourceCharacter 
  = .
```

I use the above in my own project (slightly modified), and I haven't had any problems

**Comment by dmajda** [comment]
Yes, @andreineculau is right, the JavaScript example grammar tries to stick pretty closely to the official ECMAScript grammar, which includes low-level rules such as those called by `DoubleStringCharacter`. It leads to somewhat suboptimal parser with the current code generator, but in my view, the right solution is to optimize the generated code, not the grammar. As a grammar author, you (ideally) should’t be worried about the performance too much.

As for the suggested alternative approach, the `JSON.stringify` function is used wrongly — it escapes a string possibly containing escape sequences even more instead of unescaping it. You may have meant to use `JSON.parse` but that doesn’t parse single-quoted strings and even all valid double-quoted JavaScript strings (as can be easily seen by comparing [JavaScript’s](http://www.ecma-international.org/ecma-262/5.1/#sec-A.1) and [JSON’s](http://www.ecma-international.org/ecma-262/5.1/#sec-A.8.1) lexical grammar).
