### ISSUE TITLE
Provide feedback for casetext/pegjs-import

### ISSUE THREAD

**Issue by goldibex** [pegjs/pegjs#298]
I've implemented import functionality for PEG.js via a plugin/extension called [pegjs-import](https://github.com/casetext/pegjs-import). I would be eager to hear and incorporate any feedback or design changes you might think appropriate.

**Comment by dmajda** [comment]
@goldibex Thanks for your work. Unfortunately I don’t have time to review your project (or other people’s projects in general) as I’m focusing to push 0.9.0 across the finish line. I may have a look later when I’ll work on incorporating grammar imports into PEG.js itself.

**Comment by Mingun** [comment]
First, instead of regexp magic for found `import` clauses try replace parser with new, builded on grammar with support for `import` clause. See https://github.com/pegjs/pegjs/blob/master/spec/api/plugin-api.spec.js#L95 for example.

The second, it is better to mark obviously, what rules we want to import and what aren't. If you replace a parser, you can also add support in grammar for this. Here is how I implement this approach at my fork: https://github.com/Mingun/pegjs/commit/c9b622f11057f05410d745fc615c0b34a78e6230.

With this you get the formal syntax and clear error messages.
