### ISSUE TITLE
warn function in action

### ISSUE THREAD

**Issue by malandrew** [pegjs/pegjs#325]
Currently both `expected` and `error` throw. It would be nice to have a warn(msg) function that print to console.warn() instead of throwing. 

Esprima also has parse option `tolerant`, which could be another approach. http://esprima.org/doc/

**Comment by Mingun** [comment]
This functions exists only for consistence with PEGjs error handling and for hiding error handling implementation. If you need just warning some from your action, you just may use ordinary `console.warn` call in your action.

Warning support from PEGjs needed only when #225 (or simular) will be merged.

**Comment by dmajda** [comment]
I plan to implement a warning mechanism, but I want to make it more generic so that parser users can decide what to do with emitted warnings. Your issue made me realize this is not tracked anywhere so I filed #328.

Meanwhile you can use `console.warn` directly, write a wrapper around it in the initializer, or pass some callback function/object to the parser using the `options` argument of the `parse` method which can you can then use to send warnings.

**Comment by Mingun** [comment]
Actually, this problem is already tracked in the closed pull-request #243, and it provides to users necessary flexibility as you also want, besides, it not much more difficult than the current simple approach with a throwing of exceptions: by default you won't notice a difference except that the exception throws not on each error, but on all errors found in one compilation stage. To receive  warnings and information events, it will be necessary to make a minimal amount of settings.

@dmajda, you wrote in #328:
> Note this will require a departure from the current simple API where a call to  PEG.buildParser  either returns a parser or throws an exception.

A I think, what approach from #243 is still very simple, therefore how you look at that reopen pull-request, perhaps, with some changes?

**Comment by dmajda** [comment]
@Mingun I will look, but after 1.0.0.

**Comment by StoneCypher** [comment]
Hi, I would like to investigate applying the PR from #243.  It is relatively simple and straightforward, and being able to emit errors would be quite powerful.  

I looked at @Mingun 's code; it's clean, and should be easy to test.

If we could bring this library back to a place where PRs were merge-able, this would be one of my first choices for re-investigation.

**Comment by StoneCypher** [comment]
This may be obviated by #431, I'm not really sure

There's a lot to read here
