### ISSUE TITLE
SyntaxError has undefined `stack` property

### ISSUE THREAD

**Issue by yungsters** [pegjs/pegjs#331]
It would be useful if the SyntaxError thrown by pegjs had the `stack` property:

```
this.stack = new Error().stack;
```

**Comment by dmajda** [comment]
Makes sense, custom errors should not be distinguishable from native ones in this regard. Some reference material:

* [`Error.prototype.stack` documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Stack)
* [Inheriting from the Error object - where is the message property?](http://stackoverflow.com/questions/8802845/inheriting-from-the-error-object-where-is-the-message-property)

It would be great if you or anyone could create a patch. My requirements:

* Works for both `GrammarError` (thrown by `PEG.buildParser`) and `SyntaxError` (thrown by generated parsers).
* Works in environments where `Error.prototype.stack` is not supported (in particular, IE 8-9).
* The stack trace looks exactly the same as if `Error` was thrown instead of `SyntaxError`/`GrammarError`.

**Comment by mbaumgartl** [comment]
I implemented a fix which adds the missing stack property. But I didn't pay attention to IE 8-9 so far. In my current implementation the property is set to undefined.

What is the expected behaviour if the browser doesn't support a feature?

**Comment by dmajda** [comment]
> What is the expected behaviour if a browser doesn't support a feature?

@mbaumgartl I’ll quote myself:

> Makes sense, custom errors should not be distinguishable from native ones in this regard.

So if IE sets `stack` to `"bananas"` when `new Error` is called, PEG.js should do the same. If it doesn’t set it at all, PEG.js should do the same. And so on, across all supported IE versions.
