### ISSUE TITLE
Sometimes alternative expressions are not tried.

### ISSUE THREAD

**Issue by jakwings** [pegjs/pegjs#332]
Example 1:

```
number = [0-9]+ / [0-9A-F]+

// INPUT: "3E"
// ERROR: Line 1, column 2: Expected [0-9] or end of input but "E" found.
```

Example 2:

```
letter = /* empty */ / "A"

// INPUT: "A"
// ERROR: Line 1, column 1: Expected end of input but "A" found.
```

Although such errors are avoidable by adjusting the order of expressions, I don't see it is by design.

**Comment by ragtime** [comment]
That is a property of PEG:

<http://en.wikipedia.org/wiki/Parsing_expression_grammar#Semantics>:
> The fundamental difference between context-free grammars and parsing expression grammars is that the PEG's choice operator is ordered. If the first alternative succeeds, the second alternative is ignored.

<http://pegjs.org/documentation>:
> expression<sub>1</sub> / expression</sub>2</sub> / ... / expression<sub>n</sub>
Try to match the first expression, if it does not succeed, try the second one, etc.

**Comment by jakwings** [comment]
Yes, I can see the expressions are ordered, but when the current expression failed, the next one should be tried.

**Comment by ragtime** [comment]
The problem is that the expression does not fail but successfully match a part of the input and advances the parser position.

```
number = [0-9]+ / [0-9A-F]+

// INPUT: "3E"
// ERROR: Line 1, column 2: Expected [0-9] or end of input but "E" found.
```
The "3" matches the first choice. So the "3" is consumed and the parser position is advanced to "E". But the parser is still in the same expression `[0-9]+` so he expects either the end of the input or another digit.

To solve this you could use `number = [0-9]+ ![A-F] / [0-9A-F]+` to make the match of the first expression fail as soon as a letter is read and therefore the second choice will be considered.

**Comment by jakwings** [comment]
:-O Thanks a lot. You are right. I forgot the matching is greedy and never backtracks. I'll make a pull request to the README.
