### ISSUE TITLE
Inconsistency with invert when using peg locally

### ISSUE THREAD

**Issue by jamesramsay** [pegjs/pegjs#351]
When creating a grammar on the peg online setup, I am able to use `[^\[\]]` to find any characters that aren't square brackets. However, when I use the same grammar locally I get the following error:

```
SyntaxError: Expected "!", "$", "&", "(", "*", "+", ".", "/", ";", "?", action, character class, end of input, identifier or literal but "]" found.
```

Here is an example coffee example which throw the error. Using the same grammar an input on line returns the expected result `testing testing!`.

Any assistance would be appreciated!

```coffeescript
peg = require 'pegjs'

exampleParser = peg.buildParser """
input = '[' p:placeholder ']' {
  return p
}

placeholder = x:[^\[\]]+ {
  return x.join('')
}
"""

console.log (exampleParser.parse "[testing testing!]")
```

**Comment by dmajda** [comment]
This is not a PEG.js bug, the problem lies in string escaping. You need to change `\]` in your grammar to `\\]` because simple `\]` is equivalent to `]` in CoffeeScript strings (as [this program](http://coffeescript.org/#try:s1%20%3D%20%22%22%22%0A%20%20%20%20%20%5C%5D%0A%20%20%20%20%20%22%22%22%0A%0As2%20%3D%20%22%22%22%0A%20%20%20%20%20%5D%0A%20%20%20%20%20%22%22%22%0A%0Aalert%20s1%20%3D%3D%20s2) demonstrates). For consistency, you’ll probably want to change `\[` to `\\[` too.

**Comment by jamesramsay** [comment]
Ah. Rookie error. Thanks :+1:
