### ISSUE TITLE
Semi-ambiguous parsing

### ISSUE THREAD

**Issue by hoho** [pegjs/pegjs#394]
I don't know how to name this issue, sorry in advance :).

I have a grammar like this:
```
start = eq+
eq = "==" / "==="
```

When I parse `===`, I get `SyntaxError: Expected "==", "===" or end of input but "=" found.`

Is it a bug or a feature?

Another thing looks similar.

I have a grammar:
```
start = "HELLO" (" " name)? (" " name)? " " namevalue
name = [a-z]+
value = "(" [a-z]+ ")"
namevalue = name / value
```

It parses `HELLO (abc)`, but fails to parse `HELLO abc`.

How to deal with that?

Thanks!

**Comment by YemSalat** [comment]
I might be wrong, but I think the grammar you are looking for in your first example is: `eq = "==" !"=" / "==="`

**Comment by michel-kraemer** [comment]
I haven't tested it, but my guess would be to swap `==` and `===`

    eq = "===" / "=="

**Comment by hoho** [comment]
@YemSalat @michel-kraemer I've given a simplified example, swapping the positions works for it, but here goes another example:
```
start = (token1 / token2)+
token1 = "a" [a-k]*
token2 = "b" [l-z]*
```

It fails for `abbzab` no matter what the order is.

**Comment by Mingun** [comment]
Read about that [PEG](https://en.wikipedia.org/wiki/Parsing_expression_grammar) meens and all questions will disappear directly. PEG parser is backtrack only if parse of the rule fails. In you first example:
```
start = eq+
eq = "==" / "==="
```
on an input from the infinite sequence of `=` first alternative (`==`) always matched, so no need try second alternative (`===`). If you swap alternatives, than, on input `==` first alternative (`===`) fails, but second (`==`) match.

----
In you second example:
```
start = "HELLO" (" " name)? (" " name)? " " namevalue
name = [a-z]+
value = "(" [a-z]+ ")"
namevalue = name / value
```
on input `HELLO (abc)` parser:
  1. match ` "HELLO"`
  2. unsuccesfully try match first `" " name`, but as this part is optional, it moved further
  3. unsuccesfully try match second `" " name`, but as this part is optional, it moved further
  4. match `" "`
  5. match `namevalue`:
    1. try match `name`, but fail
    2. match `value`

on input `HELLO abc` parser:
  1. match ` "HELLO"`
  2. succesfully match first `" " name`
  3. unsuccesfully try match second `" " name`, but as this part is optional, it moved further
  4. try match `" "`, but input is end, this part is required, so rule `start` not match, parser backtraking to begin of input and try another alternative
  5. but there no other alternative, so parser report parse error

So, you need rewrite you grammar, for example, as:
```
start = "HELLO" (" " name !EOF)? (" " name !EOF)? " " namevalue
name = [a-z]+
value = "(" [a-z]+ ")"
namevalue = name / value
EOF = !.// end-of-input
```
but EOF must be more complicated, if you `start` rule not top-level rule. Possibly, you can be necessary completely to rewrite grammar. For example, this not work, because after first `start` there no EOF:
```
begin = start+
start = "HELLO" (" " name !EOF)? (" " name !EOF)? " " namevalue
name = [a-z]+
value = "(" [a-z]+ ")"
namevalue = name / value
EOF = !.// end-of-input
```
----
In your last example:
```
start = (token1 / token2)+
token1 = "a" [a-k]*
token2 = "b" [l-z]*
```
on input `abbzab`:
  1. match `token1` as `abb`, unparsed `zab`
  2. try match `token1`, fail (because `zab` not begins with `a`)
  3. try match `token2`, fail (because `zab` not begins with `b`)
  4. there no other alternatives, so `start` consume only one token, `token1`. As `start` is top-level rule and there is unparsed input, parser fails, because it must consume all input

**Comment by hoho** [comment]
@Mingun thanks for the detailed response :).
