### ISSUE TITLE
Report duplicate rules and labels as multiple errors

### ISSUE THREAD

**Issue by dmajda** [pegjs/pegjs#430]
Right now, a duplicate rule is reported as one error with `location` pointing to rule's redefinition. Location of the original definition is embedded only in the error message. This is not ideal because this location is not machine-readable, which decreases usability (e.g. an editor/IDE with PEG.js integration can’t take  users to the original definition easily). The situation will be the same for soon-to-be-implemented reporting of duplicate labels.

The best solution I can see is to report duplicate rules (and labels) as multiple errors, with each error pointing at one duplicate occurrence. The error message can be simple, e.g. “Duplicate rule.”. This is essentially what [TypeScript does](https://www.typescriptlang.org/play/index.html#src=class%20C%20%7B%20%7D%0Aclass%20C%20%7B%20%7D). Note this solution requires support for producing multiple errors by `peg.generate`.

An alternative solution would be a possibility to add multiple locations to one error. But this is something users won’t expect and it would probably complicate integration with PEG.js (most tools assume one location per error).

**Comment by Mingun** [comment]
Just add to `GrammarError` (or derived exception) one property -- `originalLocation`.

**Comment by futagoza** [comment]
I think you have three options here really:

1) Embed both locations into an error as 2 different properties

  - _pro:_ maintains compatibility with pre-1.0.0 error checking tools and scripts
  - _con:_ not machine-readable, decreasing usability

2) Reimplement throw error into a multi warn/error system for PEG.js (preferred)

  - _pro:_ more non-syntax errors before throwing fatal error
  - _pro:_ pave the way for more passes/plugins to do non-fatal checks
  - _pro:_ machine-readable, increasing usability
  - _pro:_ little impact on overall compiler performance
  - _con:_ breaks compatibility with pre-1.0.0 error checking tools and scripts
  - _con:_ more work for scripts and tools to perform on a error

3) Implement an event emitter and take a callback approach to the compiler

  - _pro:_ ensures compatibility with async tools and scripts
  - _pro:_ allows use of plugins through events instead of pass's
  - _pro:_ due to async approach is the most machine-readable, increasing usability
  - _con:_ impact on overall compiler performance
  - _con:_ introduces callback hell, decreasing human-readability

**Comment by dmajda** [comment]
> Just add to `GrammarError` (or derived exception) one property -- `originalLocation`.

@Mingun I considered that, the main disadvantage of this solution in my eyes is that it’s unsystematic and requires special treatment of duplicate rule/label errors by the consumer.

@futagoza I mostly agree with you and your list of pros & cons, I was also thinking about your 2 and 3. I separated the discussion about the error/warning reporting mechanism into #431 so that it isn’t spread over all the issues which will use it. This issue should now only cover the simple task of using the mechanism for duplicate rule/label errors once it is in place.
