### ISSUE TITLE
Make it possible to use peg.generate as a module function

### ISSUE THREAD

**Issue by futagoza** [pegjs/pegjs#433]
This works fine:
```javascript
var peg = require('pegjs')
peg.generate(...)
```
But this:
```javascript
var generate = require('pegjs').generate
generate(...)
```
throws a type error:
```
C:\projects\ePEG.js\node_modules\pegjs-dev\lib\peg.js:44
          parser: this.parser,
                      ^

TypeError: Cannot read property 'parser' of undefined
```

_NOTE:_ Just so you know, [pegjs-dev](https://www.npmjs.com/package/pegjs-dev) is a npm module that I maintain that is a mirror of [https://github.com/pegjs/pegjs](https://github.com/pegjs/pegjs)

**Comment by dmajda** [comment]
When I was designing PEG.js, I was thinking about `peg` as an *object*, not as a *module*, and wrote the code accordingly (which mostly means I didn’t actively try to avoid `this`). However, it seems users like you see things little differently (this is not the first time this issue was raised), so I decided to fix things so that both the generator and generated parser can be used as modules (note this required getting rid of the `parser` variable in generated parsers). Commits coming in a minute.

See also [this discussion] (https://github.com/pegjs/pegjs/issues/423#issuecomment-214762654).
