### ISSUE TITLE
Rules starting with the same pattern do not work as alternatives to each other

### ISSUE THREAD

**Issue by cekdahl** [pegjs/pegjs#435]
Consider the rule

    start = [a-z]+
    / [0-9]+ '!'

in a grammar.

    abc // matches
    123! // matches

Now change the alternate rule to create the grammar

    start = [a-z]+
    / [a-z]+ '!'

then 

    abc // matches
    abc! // does not match

Please correct me if I'm wrong, but I don't believe this is how it's supposed to work.

**Comment by dmajda** [comment]
For input `abc!`, the first alternative (`[a-z]+`) matches a part of the input, meaning the second alternative (`[a-z]+ '!'`) isn’t tried at all. The result is that the matching expression doesn’t consume the whole input, which is why parsing fails at the end.

This is how PEG.js is supposed to work. You need to order alternatives in a choice so that the ones potentially matching longer inputs go first.
