### ISSUE TITLE
Add `comment` nodes to AST

### ISSUE THREAD

**Issue by Mingun** [pegjs/pegjs#458]
Will be great if comments in grammar also included is AST. It will be useful for creation of full-featured plug-ins to IDE's. For a start there is a wish to have a possibility just of existence of comments in AST, but, maybe, it will be possible to find a way to associate them with other AST nodes. Several intuitively expected examples of association:
```pegjs
// rule1 first comment
// (this is also included in first comment)
rule1 = 'rule1'; // rule1 second comment
// this is not rule1 comment or rule2 comment

/* multiline
 * rule2 comment
 */
rule2 = 'rule2' /*also rule2 comment*/

rule3 'rule3' // rule3 comment
  // first alternative comment
  = 'a' 'b'
  /* second alternative comment */
  /* in several */
  // lines
  / ('c' / 'd')
  / 'ef' // third alternative comment
  / 'gh' /* this is also should work */
  ;

rule4
  // first sequence element comment
  = 'a'
  /* second sequence
element comment
*/  'b'
    [c-e] // third sequence element comment
    .* /* last sequence element comment */
```

**Comment by dmajda** [comment]
While I can imagine adding comments to the AST would be useful for some use cases, the comments are not needed by PEG.js itself and processing them would complicate the parser code (probably not a lot, but still). Because of this, I’m saying “no” at this point.

I’d encourage you (or anyone else) to fork the parser and prototype this as a plugin. Then, if the plugin becomes reasonably popular (meaning it becomes used by others to write their tools), I’ll consider adding this to the mainline.

**Comment by YemSalat** [comment]
Just my 2 cents on this matter. I have personally been using PEG.js mainly to generate parsers that produce output 'directly', instead of generating an AST (we have JavaScript 'built-in', so why not?) E.g. something similar to the arithmetics grammar example, but usually a bit more complex then that.
And I find more uses for PEG.js that way. I personally don't think that producing ASTs should be the sort of 'main' thing  that PEG.js does.

In addition to that, if you are building an AST - you can already add any comments you like. Maybe having more built-in functions or properties like `location()` would be more useful? E.g. if you could access global properties like `currentRule` that returns the AST for the current grammar rule that pegjs is parsing?

**Comment by dmajda** [comment]
@YemSalat This issue is about the AST produced by PEG.js grammar parser (the one available as `peg.parser`), not about user-generated parsers.

**Comment by Mingun** [comment]
For support of comments it is necessary to change parser grammar. The plug-in replacing a parser actually completely replaces pegjs. I don't see why pegjs is in that case necessary. So the idea of such plug-in becomes senseless.

**Comment by dmajda** [comment]
@Mingun You may or may not be right depending on what exactly you want to do with the enhanced parser. For example, a full-featured IDE plugin you mentioned in the description could use not only the parser, but also a part of the PEG.js pipeline (e.g. to display semantic errors).

In any case, my point is that a comment-processing parser should be developed outside the mainline and only included if it proves useful enough. Whether there would be a plugin wrapping it or not is not that important.
