### ISSUE TITLE
why not use empty string('') instead of null to call the function when optional string is empty ?

### ISSUE THREAD

**Issue by cuixiping** [pegjs/pegjs#465]
A simple example:
```
start = sign:sign? digits:digits { return +(sign+digits); } 
digits = a:digit b:digits? { return a+b; }
digit = [0-9] 
sign = '+' / '-'
```
It can parse `+123` to `123` correctly, but parse `123` to `NaN`  incorrectly. 

Now I must write like this:
```
start = sign:sign? digits:digits { return +((sign||'')+digits); }   //use (sign||'') to convert null to ''
digits = a:digit b:digits? { return a+(b||''); }  //use (b||'') to convert null to ''
digit = [0-9] 
sign = '+' / '-'
```

so, why not use empty string('') instead of null to call the function?

**Comment by dmajda** [comment]
PEG.js originally did what you suggest but I [changed](https://github.com/pegjs/pegjs/commit/86769a6c5c46efeb77020d91c0e4837020101b6d) the behavior to the current one in 0.8.0.

The reason is that while returning an empty string may be useful in lexer-level rules (like the ones in your example), it tends to complicate more high-level rules, which usually dominate the grammar. In these rules, returned values are typically objects and `null` returned from `?` is often embedded right into the resulting AST.

Beside practical reasons, returning `null` feels more natural to me and it is more consistent with values that other expressions return.

To avoid convoluted actions in lexical portions of grammars, you can use the `text` function or the `$` operator. Your example can be simplified like this:

```pegjs
start = sign:sign? digits:digits { return +text(); }
digits = a:digit b:digits?
digit = [0-9] 
sign = '+' / '-'
```

or like this:

```pegjs
start = number:$(sign? digits) { return +number; }
digits = a:digit b:digits?
digit = [0-9] 
sign = '+' / '-'
```

(Personally, I’d avoid abusing the `+` operator for conversion and use `parseInt` or `Number` call for that.)
