### ISSUE TITLE
Is it possible that "$ expression" only returns the matched text but does not execute all the action codes of the expression?

### ISSUE THREAD

**Issue by shenfe** [pegjs/pegjs#486]
As the title says.

**Comment by Mingun** [comment]
No, this is impossible without rewriting grammar. You can achieve it if your actions return callback which needs to be called to receive result. If besides you have semantic predicates (`&{...}` or `!{...}`), then anyway, for them it is necessary to materialize result of a call of actions since result of a condition can depend on it.

It is possible to write a plug-in which will do the specified actions automatically for specially marked actions. As I offered in #214, it can look, for example, so:
```pegjs
simple = expr;
complex = $expr
expr = l:[0-9] '*' r:[0-9] ^{ return l*r; }
```
which can be expanded to
```pegjs
simple = _1:expr { return _1(); }
complex = $expr
expr = l:[0-9] '*' r:[0-9] { return () => l*r; }
```
Well, now `complex` rule will be unavailible, according to existing rules, because it is not in `allowedStartRules` list (only first tule in it), but with small tuning you can resolve this problem.

**Comment by futagoza** [comment]
Closing, as @Mingun has answered the question.
