### ISSUE TITLE
Case that doesn't match won't let the parser get to the following case that matches

### ISSUE THREAD

**Issue by Hellayne** [pegjs/pegjs#502]
Hello,

I wrote a grammar and encountered an issue, input was {name: {$in: rs}}.

> Start = Query // Start rule
> 
> Query
>  = "{" body:Body "}" {return body;}
> 
> Body
>  = field:Field {return "WHERE " + field;} // Simple query with fields
>  / key:Key _? ":" _? "{" "$in" _? ":" _? valueArray:ValueArray "}" {return "r";}
> 
> Field // First field
>  = key:Key _? ":" _? value:Value next:NextField?
> 	{
> 		if(next != null) return key + " = " + value + next; // Multiple fields
>         else return key + " = " + value; // Single field
>     }
> 
> NextField // Following fields
>  = _? "," _? key:Key _? ":" _? value:Value next:NextField?
> 	{
>     	if(next != null) return " AND " + key + " = " + value + next; // Multiple fields
>     	return " AND " + key + " = " + value; // Single field
>     }
> 
> Key // Field key
>  = expr:[_a-zA-Z0-9]* {return expr.join("")};
> 
> Value // Field value
>  = expr:[_a-zA-Z0-9]* {return expr.join("")};
> 
> NextValue
>  = _? "," _? expr:[_a-zA-Z0-9]* nextValue:NextValue?
> 
> ValueArray // Array of values
>  = arrayName:[_a-zA-Z0-9]*
>  / "[" value:Value nextValue:NextValue? "]"
> 
> _ "whitespace"
>  = [ \t\n\r]*

It seemed like it tried to match the first case defined in the Body rule even though it wouldn't lead to a match, so I did swap the two cases:

> Body
>  = key:Key _? ":" _? "{" "$in" _? ":" _? valueArray:ValueArray "}" {return "r";}
>  / field:Field {return "WHERE " + field;} // Simple query with fields

With this order, the input was parsed correctly. Unless I misunderstood the documentation, the order should not matter right? Or did I actually write incorrect rules causing this?

Please forgive me if this issue had already been reported, I scanned through them and didn't see any similar titles, or if this happened to be a faulty grammar.

Hellayne

**Comment by jodevsa** [comment]
#### i'm new too to PEG , but from my understanding order matters!

```
Body= field:Field {return "WHERE " + field;} // Simple query with fields
/ key:Key _? ":" _? "{" "$in" _? ":" _? valueArray:ValueArray "}" {return "r";}
field=key:Key _? ":" _? value:Value next:NextField?
```

```
{body:{$in:2}} //input 1
{body:1} //input 2

```
first you have to know that peg does not try all paths you define, peg will try to match the first working sub-path and continue with it's grammar (the `Field` grammar).

Due to the fact that both path's contain's the sub -grammar ` "{" key ":" ` peg will choose the first one, and continue with that grammar, when peg reach's value array grammar, it will test "{$in" input against it , which result's in parsing error since "{$in" does not belong to value array grammar.

#### so yes, order is important .

**Comment by Hellayne** [comment]
Thank you for your answer, I understand better now. I thought it would try any remaining paths if the current path failed halfway. What you said does make sense, maybe I missed how things were processed when I read the documentation.

**Comment by jodevsa** [comment]
@Hellayne  Happy to help !

**Comment by jodevsa** [comment]
@Hellayne 
Checkout [PEGJS-BackTrace](https://github.com/okaxaki/pegjs-backtrace), i'm sure it will help you understand more !

**Comment by futagoza** [comment]
@Hellayne As @jodevsa mentioned, order is very important when writing a PEG based grammar.
See this Wikipedia article for more information: https://en.wikipedia.org/wiki/Parsing_expression_grammar#Semantics

Also, a tip:
You seem to be using `_?` to ignore whitespace, but since you are using a [zero_or_more expression](https://github.com/pegjs/pegjs#expression-) for your whitespace rule (`_ = [ \t\n\r]*`) you don't need to use `?`
