### ISSUE TITLE
Added pegjs plugin for TypeScript

### ISSUE THREAD

**Issue by pjmolina** [pegjs/pegjs#514]
Hi. 
I was needing a good parser in TypeScript so I decided to write a plugin to retarget pegjs output JS code to be exposed as TypeScript.

Main differences are linting issues (tslint) plus exports a la TypeScript).  Repo: [ts-pegjs](https://github.com/metadevpro/ts-pegjs)

I added it to the [wiki plugins page](https://github.com/pegjs/pegjs/wiki/Plugins).
Feel free to test it as needed. Feedback is welcome!

**Comment by futagoza** [comment]
Thanks for the heads up @pjmolina, but next time I think it would be better to post this kind of news to either https://twitter.com/peg_js or https://groups.google.com/forum/#!forum/pegjs 😄

**Comment by pjmolina** [comment]
Sure, I will do next time! Sorry for the off-topic. 
Thanks for the tweet about it!

**Comment by polkovnikov-ph** [comment]
@futagoza Github is usually much higher in search results. I was happy to find the information here.

I've seen a lot of repos where any kind of feedback is appreciated as github issues, even though this feature was made mostly for bug reports. They have a tag "not-an-issue" for such purposes and just close the issue immediately, because there is no further input needed from developers' side. It might be a bit annoying for developers, but in the end it's very helpful for community.

Please, reevaluate your policy, and thanks for great job anyway!
