### ISSUE TITLE
https://pegjs.org/ is down

### ISSUE THREAD

**Issue by Hellayne** [pegjs/pegjs#515]
Hello!
It looks like the website is currently down. I've been trying to access it to work on my project for 4 hours now. Last time I accessed it was yesterday around 6PM UTC+2.

Many thanks in advance!

**Comment by felipellrocha** [comment]
Bump. I just noticed this as well...

**Comment by iddogino** [comment]
Bumping as well

**Comment by futagoza** [comment]
Hi, sorry folks, just got home and noticed it was down.

Probally happened because I changed the nameservers 2 days ago while trying to fix the problem of the apex domain `pegjs.org` going down every week. Will try and get this fixed asap.

Thanks for the issue, was able to see this as soon as my phone connected to my WIFI and got my email, still in my shoes and jacket while typing this 😄

**Comment by iddogino** [comment]
@futagoza great to hear. Let me know if there's anything I can be helpful with.

**Comment by futagoza** [comment]
Okay, seem's like the issue is resolved now (both this and weekly down times).
