### ISSUE TITLE
Recent features are unavailable through npm-installed pegjs

### ISSUE THREAD

**Issue by YairRand** [pegjs/pegjs#521]
When using pegjs installed through npm, recent features such as the `es` format mentioned in the documentation are unavailable.

I'm not completely sure how npm works, so this is speculation, but I suspect this might have something to do with the fact that the version number hasn't been updated since August 19, 2016. It appears that more recent changes aren't part of the default installed version.

**Comment by skratchdot** [comment]
That's because a new version has not be tagged or released yet.  You can use npm to install packages directly from git if you want the version that's in master:

```
npm install pegjs/pegjs#master
```

Here's the diff between master and the last published version: https://github.com/pegjs/pegjs/compare/v0.10.0...master

**Comment by futagoza** [comment]
You can also try the [pegjs-dev](https://www.npmjs.com/package/pegjs-dev) package hosted on NPM. It's meant to be a simpler alternative to including the PEG.js repo directly like @skratchdot showed, but will need changes to require call's if you use PEG.js as a library (require `pegjs-dev` instead of `pegjs`), but if you use it via the `pegjs` command tool, there's no changes required 😄
