### ISSUE TITLE
install dev package causes error on windows (not sure if this is platform independent)

### ISSUE THREAD

**Issue by jtenner** [pegjs/pegjs#535]
```
npm ERR! path C:\Users\jtenner\Desktop\projects\papl\node_modules\pegjs-dev\bin\peg
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\jtenner\Desktop\projects\papl\node_modules\pegjs-de
v\bin\peg'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jtenner\AppData\Roaming\npm-cache\_logs\2017-09-15T16_15_05_431Z-debug.log
```

Can be fixed by simply git cloning the dev repo to node_modules, but I can't deploy the project for obvious reasons.

**Comment by futagoza** [comment]
Sorry about this @jtenner, I forgot to update the files field in the `package.json` when I split the bin file into 3 files. I've fixed this bug in [a commit I just pushed](https://github.com/pegjs/pegjs/commit/14948dad9394c311b635bc52b2b9151e32c59e89), and have also published [pegjs-dev@0.10.0-162](https://www.npmjs.com/package/pegjs-dev) that contains the change.

**Comment by jtenner** [comment]
Not a problem! I love this tool, very much. But it does seem that it can't find bin\peg still

```
PS C:\Users\jtenner\Desktop\projects\papl> npm install --save  pegjs-dev@0.10.0-162
npm WARN papl@1.0.0 No description
npm WARN papl@1.0.0 No repository field.

npm ERR! path C:\Users\jtenner\Desktop\projects\papl\node_modules\pegjs-dev\bin\peg
npm ERR! code ENOENTs\jtenner\AppData\Roaming\npm-cache\_logs\2017-09-15T23_02_56_905Z-debug.log
npm ERR! errno -4058Desktop\projects\papl>
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\jtenner\Desktop\projects\papl\node_modules\pegjs-dev\bin\peg'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jtenner\AppData\Roaming\npm-cache\_logs\2017-09-15T23_03_34_097Z-debug.log
```

**Comment by futagoza** [comment]
Fixed in [latest commit](https://github.com/pegjs/pegjs/commit/a1ad351c2c745ecf60a3f0a75720348206971066) ([pegjs-dev@0.10.0-163](https://www.npmjs.com/package/pegjs-dev)) by adding the `.js` extension in the bin field.

I don't know why, but it seems like the bin field isn't being resolved the way the lib field is, but when I run `node bin/peg -v` from the root of the PEG.js repository I get the expected result, so npm install is probably either using a different file resolver, although I'm sure I've never had this issue before with bin files.

Sorry about this @jtenner, and thanks for the heads up, I updated the files field and expected it to just work, pushed the changes, updates the issue, then started playing on my PS4 🤣

**Comment by jtenner** [comment]
Thanks again! I just checked installing from the main repo and it works fine. Thank you for all the work you do on this project. 👍
