### ISSUE TITLE
Calling expected with braces breaks the parser

### ISSUE THREAD

**Issue by lukasolson** [pegjs/pegjs#576]
When I attempt to use the following grammar:

```
foo
= '' { return expected('{'); }
```

It won't even parse. Apparently this has something to do with the braces, but I'm not sure why that would cause a problem.

**Comment by pjmolina** [comment]
The repeated remark in the [documentation](https://pegjs.org/documentation) refers explicitly to this: _"Note that curly braces in the predicate code must be balanced."_ 

Possibly the cause is related to a parsing strategy taken with some limitations.

As a work-around, in your case: you can pre-declare two constants and use them inside the predicate:

```js
const LBRACE='{';
const RBRACE='}';
...

foo= '' { return expected(LBRACE); }

```

**Comment by lukasolson** [comment]
Thanks for the workaround :)

Hmm, I was under the impression that that comment referred to unbalanced code braces, not quoted braces, which don't actually act like code braces. Is there a technical reason this isn't feasible to support?

**Comment by balagge** [comment]
This is a duplicate of an old issue that is reported over and over again, see the original #89.

Other duplicates:
https://github.com/pegjs/pegjs/issues?utf8=%E2%9C%93&q=is%3Aissue+brace+
