### ISSUE TITLE
Support of IE11

### ISSUE THREAD

**Issue by arnaudlewis** [pegjs/pegjs#583]
Currently, the build contains some "eval" which prevent it from working with ie11.
Do you have a solution for it?
Or maybe we could change the build a bit. I'm willing to make a pull request if you have some suggestions.

**Comment by futagoza** [comment]
Hey @arnaudlewis, thanks for bringing it up.

I've got it working in IE11 (https://pegjs.org/development/try), and the [Benchmark Suite](https://pegjs.org/benchmark) is also running in IE11 but I can't get the [Spec Suite](https://pegjs.org/spec) running because the dependencies don't support IE11 🤣

**Comment by arnaudlewis** [comment]
Thanks for the quick response @futagoza, can you just tell me when it's gonna be released on npm?

**Comment by srenault** [comment]
Any news on that?
