### ISSUE TITLE
Strange extra action evaluation

### ISSUE THREAD

**Issue by vsemozhetbyt** [pegjs/pegjs#643]
### Issue type

- **Bug Report:** yes
- **Feature Request:** no
- **Question:** no
- **Not an issue:** no

### Prerequisites

- **Can you reproduce the issue?:** yes
- **Did you search the repository issues?:** yes
- **Did you check the forums?:** no
- **Did you perform a web search (google, yahoo, etc)?:** no

### Description

Say, I have a string with mandatory `'a'` literals and optional `'x'` literals around them. I want to count the actual amount of `'x'`.

### Steps to Reproduce

**Example code:**

```js
const result = require('pegjs')
  .generate(`
    { let xx = 0; }

    root  =  (x? 'a')+ x? { return xx; }

    x  =  'x'  { xx++; }
  `)
  .parse('ax');

console.log(result);
```

**Expected behavior:**

The count is `1`.

**Actual behavior:**

The count is `2`.

### Software

- **PEG.js:** pegjs@dev (0.11.0-master.b7b87ea)
- **Node.js:** 13.9.0
- **NPM or Yarn:** 6.13.7
- **Browser:** -
- **OS:** Windows 7 x64
- **Editor:** -

**Comment by Mingun** [comment]
This is not bug. Parsing is performed in the following order
1. Try to match `x` in `(x? 'a')+` => fail
2. `x?` always matched, so first element in sequence `x? 'a'` is matched, position is not changed (still `0`)
3. Try to match `'a'` => success, position now is `1`
4. Sequence is matched iif all elements of sequence is matched. Because both `x?` and `'a'` is matched, sequence is matched
5. Because of repeat in `(x? 'a')+` try to match `x` again => success, position is `2`, `xx == 1`
6. `x?` always matched, so first element in sequence `x? 'a'` is matched, position is not changed (still `2`)
7. Try to match `'a'` => fail, position is not changed (still `2`)
8. Sequence is matched iif all elements of sequence is matched. Because `'a'` is not matched, sequence is not matched. Backtrace to begin of sequence => position returned to `1`
9. `(...)+` is matched iif it matched one or more times. Now is is matched 1 time, so repetition is matched. Position is `1`
10. Try to match `x` in `(...)+ x?` => success. Position is `2`, `xx == 2`
11. `x?` always matched
12. Sequence is matched iif all elements of sequence is matched. Because both `(x? 'a')+` and `x?` is matched, sequence is matched.
13. Because grammar is finished, it implicitly required EOF. End of input reached => so grammar is matched. Result is `xx == 2`.

**Comment by vsemozhetbyt** [comment]
Thank you. Maybe it is worth to mention in the docs that due to backtracking, side-effect actions need cautions.
