### ISSUE TITLE
Other useful debugging output

### ISSUE THREAD

**Issue by celer** [pegjs/pegjs#9]
So one thing that would be really awesome is some more debugging output. When I have a parser that doesn't work and is already producing a structured output, I am left either having to gut it to get back to something that lets me look at the structured output and see where the error is in my grammar. 

So it would be nice if there were some command line options for the parser generator, which caused the parser to dump debugging info, such as which rule fired, and what characters were captured as part of the rule.

**Comment by hegemonic** [comment]
I would _love_ to have a `--trace` option. I'm currently trying to figure out where a parser is failing, and it's been an awfully slow process. With a trace option, I could have found the answer very quickly.

**Comment by christofmuc** [comment]
+1 here. I totally totally love PEG.js and have used it for more than once thing already, but debugging a grammar is pita. Will try patching with the  suggestion above.

**Comment by dmajda** [comment]
In the past few weeks I worked on this issue and added tracing support to PEG.js-generated parsers. Instead of implementing a simple static solution, I added a flexible API which allows users to pass their own *tracer* to a parser. This tracer receives events about parsing progress and can decide what to do with them (display, store, etc.). There is also a built-in default tracer (used when no tracer is supplied by the user) that logs events to the console in a simple format.

Details can be found in the [commit introducing tracing support](https://github.com/pegjs/pegjs/commit/da57118a43a904f753d44d407994cf0b36358adc).

The API is currently somewhat experimental (which is why it isn’t documented properly yet) and I expect it will evolve over time as experience is gained.

The default tracer is also somewhat bare-bones. I hope that PEG.js user community will develop more sophisticated tracers over time and I’ll be able to integrate their best ideas into the default tracer.

Big thanks goes to @ganeshv who [implemented](https://github.com/pegjs/pegjs/issues/121) initial tracing support for PEG.js which I used as a source of inspiration.

With that, I am closing this issue. Request for improving the API or the default tracer should go into separate issues.
